### ISSUE TITLE
System failure

### ISSUE THREAD

**Issue by kayradinaryus** [ilpersi/Popmundo-Utils#4] opened 2024-02-20 07:39 UTC
The game frequently locks me out of the system while the app is open.

**Comment by ilpersi** [comment] 2024-03-13 14:31
Can you please provide more details?

What features do you use? When exactly are you logged out?

**Comment by ilpersi** [comment] 2024-05-29 16:14
I haven't got any feedback in months, so I am closing this. If the issue is still happening, please feel free to open a new one.

**Closed by ilpersi** 2024-05-29 16:14 UTC
